name: projet_flutter
description: A Flutter project for displaying photo frames with action buttons
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  dio: ^5.3.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
